name: RSS to README
description: Replaces a section of the repo's README with the contents of an RSS feed
inputs:
  feed-url:
    required: true
    description: A URL to an RSS feed.
  readme-section:
    required: true
    description: The name of the section of the README to update.
  max:
    default: 5
    description: The maximum number of RSS feed items to show.
  template:
    default: '* [{{ title }}]({{ link }})'
    description: The template to use for each item in the RSS feed. These are joined by a new line.
  path:
    default: 'README.md'
    description: The path to the README file
  github_token:
    default: ${{ github.token }}
  branch:
    default: ${{ github.event.repository.default_branch }}
    description: The target branch to update.
  empty-commits:
    default: 'true'
    description: set to `false` to disallow empty commits when there are no changes
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: activity
  color: red
