name: RSS to README
description: Replaces a section of the repo's README with the contents of an RSS feed
inputs:
  feed-url: 
    required: true
    description: A URL to an RSS feed.
  readme-section:
    required: true
    description: The name of the section of the README to update.
  max:
    default: 5
    description: The maximum number of RSS feed items to show.
  pre_template:
    default: ''
    description: Any additional text or tag goes here.
  template:
    default: '* [{{ title }}]({{ link }})'
    description: The template to use for each item in the RSS feed. These are joined by a new line.
  post_template:
    default: ''
    description: Any additional text or tag goes here.
  github_token:
    default: ${{ github.token }}
runs:
  using: node12
  main: dist/index.js
branding:
  icon: activity
  color: red
